/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shelajev' at '3/30/15 12:10 PM' with Gradle 2.2.1
 *
 * @author shelajev, @date 3/30/15 12:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
